"""Entry point: `uv run generate`.

Writes `generate/library.fasta` (50,000 sequences) and `generate/top.fasta`
(100 sequences). Output is byte-identical across runs for a fixed seed, which
the organizers' compliance script checks by running this twice and diffing bytes.

Determinism
-----------
* All randomness flows through a single `numpy.random.default_rng(seed)`
  (PCG64, bit-identical across platforms by specification).
* The neural sampler runs in **float64 on CPU**; logits are quantized to 1e-6
  before sampling, which leaves ~8 orders of magnitude of margin over the
  ~1e-14 disagreement float64 BLAS can show between machines.
* Every ranking uses a quantized score with a lexicographic tiebreak on the
  sequence string, so sub-ulp differences cannot reorder anything.
* FASTA is written with explicit "\\n" newlines, and `.gitattributes` pins LF,
  so the committed bytes match the regenerated bytes on any platform.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

from . import descriptors as D
from . import scoring
from .constants import (
    DEFAULT_SEED,
    LIBRARY_FILENAME,
    LIBRARY_SIZE,
    TOP_FILENAME,
    TOP_SIZE,
)
from .fasta import read_sequences, write_fasta
from .filters import ReferenceIndex
from .paths import find_resource
from .pipeline import collect_pool, select_library, select_top

REFERENCE_FASTA = "data/antibacterial.fasta"
TRANSFORMER_CKPT = "checkpoint/transformer.npz"
MARKOV_CKPT = "checkpoint/markov.npz"
ORACLE_CKPT = "checkpoint/oracles.pkl"

# Selection temperature for the library, chosen by the sweep in
# eval/selection_sweep.py to trade ConformityScore against FBD/Recall.
DEFAULT_TAU = 0.5

# Pool size as a multiple of the library. The transformer loses <1% to
# deduplication and ~0% to the novelty filter, so the multiplier exists to give
# the density-temperature selection something to select *from*, not to cover
# attrition.
DEFAULT_OVERSAMPLE = 2.0

# Activity conditioning bucket (0-7). Bucket 7 corresponds to the most
# canonically AMP-like decile of the training database under the adversarial
# classifier. `None` falls back to the classifier-free-guidance null token.
DEFAULT_ACTIVITY_BUCKET = None  # measured: steering activity costs more FBD/Recall than it buys

# Sampling temperature. Below 1.0 concentrates on higher-likelihood (more
# typical) sequences, which measurably raises predicted activity at a small
# cost in diversity.
DEFAULT_TEMPERATURE = 1.0


def build_sampler(kind: str, reference: list[str], verbose: bool,
                  *, activity_bucket: int | None = None, temperature: float = 1.0):
    """Return `sampler(n, rng) -> list[str]` for the chosen generator."""
    if kind == "transformer":
        from .neural import (
            AMPH_EDGES,
            CHARGE_EDGES,
            LENGTH_EDGES,
            NumpyPeptideLM,
            bucketize,
            condition_tokens,
        )

        model = NumpyPeptideLM.load(find_resource(TRANSFORMER_CKPT))

        # Length / charge / amphiphilicity conditioning is drawn from the
        # reference AMPs' own joint bucket distribution. Measurement showed
        # hand-picked "targeted" buckets are worse on every metric including
        # ConformityScore: the AMP charge mode is near +3, and steering to +7
        # moved the library off the mode rather than onto it. Reproducing the
        # empirical marginals is the right prior; concentration toward the mode
        # is applied later, by selection.
        lb = bucketize(np.array([len(s) for s in reference], dtype=np.float64), LENGTH_EDGES)
        cb = bucketize(D.net_charge(reference), CHARGE_EDGES)
        ab = bucketize(D.hydrophobic_moment(reference), AMPH_EDGES)

        def sampler(n: int, rng: np.random.Generator) -> list[str]:
            pick = rng.integers(0, len(reference), size=n)
            # The activity axis is steered rather than sampled empirically: it
            # asks the model for peptides as canonically AMP-like as the best
            # entries in the training database, which is the one axis where
            # reproducing the database average is not what we want.
            act = np.full(n, activity_bucket, dtype=np.int64) if activity_bucket is not None else None
            cond = condition_tokens(lb[pick], cb[pick], ab[pick], act)
            return model.sample(
                n, rng, cond=cond, temperature=temperature,
                batch_size=512, progress=verbose,
            )

        return sampler

    from .model import MarkovPeptideModel

    ckpt = MARKOV_CKPT
    model = MarkovPeptideModel.load(find_resource(ckpt))

    def sampler(n: int, rng: np.random.Generator) -> list[str]:
        return model.sample(n, rng)

    return sampler


def main() -> None:
    entry_point = Path(sys.argv[0]).stem

    parser = argparse.ArgumentParser(description="Generate an AMP Challenge submission.")
    parser.add_argument("--n-sequences", type=int, default=LIBRARY_SIZE)
    parser.add_argument("--top-k", type=int, default=TOP_SIZE)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--generator", default="transformer",
                        choices=["transformer", "markov"])
    parser.add_argument("--tau", type=float, default=DEFAULT_TAU)
    parser.add_argument("--oversample", type=float, default=DEFAULT_OVERSAMPLE)
    parser.add_argument("--activity-bucket", type=int, default=DEFAULT_ACTIVITY_BUCKET)
    parser.add_argument("--temperature", type=float, default=DEFAULT_TEMPERATURE)
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    verbose = not args.quiet
    rng = np.random.default_rng(args.seed)

    if verbose:
        print(f"[1/6] Loading reference database", flush=True)
    reference = read_sequences(find_resource(REFERENCE_FASTA))
    index = ReferenceIndex(reference)
    density = scoring.ConformityDensity(reference, seed=args.seed)

    if verbose:
        print(f"[2/6] Loading generator: {args.generator}", flush=True)
    sampler = build_sampler(
        args.generator, reference, verbose,
        activity_bucket=args.activity_bucket, temperature=args.temperature,
    )

    target_pool = int(args.n_sequences * args.oversample)
    if verbose:
        print(f"[3/6] Sampling pool of {target_pool:,}", flush=True)
    pool = collect_pool(sampler, index, target=target_pool, rng=rng, verbose=verbose)

    if verbose:
        print(f"[4/6] Selecting library of {args.n_sequences:,} (tau={args.tau})", flush=True)
    library = select_library(
        pool, density, n_select=args.n_sequences, tau=args.tau, rng=rng, verbose=verbose
    )

    if verbose:
        print(f"[5/6] Selecting top {args.top_k}", flush=True)
    oracle_path = find_resource(ORACLE_CKPT)
    from .oracles import OracleEnsemble

    oracles = OracleEnsemble.load(oracle_path)
    top, stats = select_top(library, index, oracles, top_k=args.top_k, verbose=verbose)

    out_dir = Path(entry_point)
    write_fasta(library, out_dir / LIBRARY_FILENAME)
    write_fasta(top, out_dir / TOP_FILENAME)

    if verbose:
        print(f"[6/6] Wrote {len(library):,} -> {out_dir / LIBRARY_FILENAME}", flush=True)
        print(f"      Wrote {len(top)} -> {out_dir / TOP_FILENAME}", flush=True)
        print("      top-100 predicted profile:")
        for k, v in stats.items():
            print(f"        {k}: {v:.4f}")
        Path("checkpoint/last_run_stats.json").write_text(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()
